name: um-ios-test-coverage
version: 1.0.3
title: UM iOS Test Coverage
description: Runs UM iOS Unit Tests and Generates Coverage Report
author: https://github.com/thanyalukj
requirements: []
configuration:
  properties:
    platform:
      type: string
      enum: ['ios-library', 'react-library']
    workspace:
      type: string
    scheme:
      type: string
  additionalProperties: false
