#!/usr/bin/env bash
set -euo pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

## Source functions.bash based on environment
## local environment = BUILDKITE_BUILD_ID is not set
## Buildkite environment = BUILDKITE_BUILD_ID is set
BUILD_ID=${BUILDKITE_BUILD_ID:-""}
if [ ! $BUILD_ID == "" ]; then
  # shellcheck source=lib/functions.bash
  # shellcheck disable=SC1091
  source "$DIR/../lib/xccov-to-sonarqube-generic.bash"
fi

## Setup variables from the plugin properties
PLATFORM="${BUILDKITE_PLUGIN_UM_IOS_TEST_COVERAGE_PLATFORM:-undefined}"
WORKSPACE="$BUILDKITE_PLUGIN_UM_IOS_TEST_COVERAGE_WORKSPACE"
SCHEME="$BUILDKITE_PLUGIN_UM_IOS_TEST_COVERAGE_SCHEME"

## Setup variables
SKIP=$(buildkite-agent meta-data get 'skip-test' --default 'true')
SIMULATOR="iPhone 16"
OS_VERSION="18.2"
DESTINATION="platform=iOS Simulator,name=${SIMULATOR},OS=${OS_VERSION}"
BUILD_WRAPPER_OUTPUT_DIR="build_wrapper_output_directory"
RESULT_FILE="sonarqube-generic-coverage.xml"

# Select Xcode 16.2
sudo xcode-select --switch /Applications/Xcode_16.2.app/Contents/Developer

function run_ios_unit_tests_and_sonar() {
  echo "--- :test_tube: Running iOS Unit Tests..."

  rbenv install --skip-existing

  # Install any missing gems
  bundle install --quiet

  # Below code stolen from https://github.com/actions/runner-images/blob/5a6e2158591c3f3b0c732691694d061fea8f792e/images/macos/scripts/build/configure-xcode.sh

  # quit the CoreSimulatorService
  launchctl remove com.apple.CoreSimulator.CoreSimulatorService || true
  # add sleep to let CoreSimulatorService to exit
  sleep 3
  # erase the devices
  xcrun simctl erase all
  # add sleep due to sometimes "xcrun simctl list" takes more than a few moments and script fails when trying to remove CoreSimulatorSerivce
  sleep 10

  # Set and boot the desired simulator with retries
  echo "~~~ Set and boot the desired simulator with retries"
  RETRIES=5
  for i in $(seq 1 $RETRIES); do
    if xcrun simctl boot "$SIMULATOR"; then
      echo "Simulator booted successfully"
      break
    else
      echo "Failed to boot simulator, retrying... ($i/$RETRIES)"
      sleep 10
    fi
  done

  # Add sleep to ensure the simulator is fully booted
  sleep 10

  BASEDIR=$(pwd)

  echo "~~~ Install iOS dependencies"
  cd ios/library/test-harness
  bundle install --quiet
  bundle exec pod install

  echo "~~~ build-wrapper"
  build-wrapper --out-dir $BUILD_WRAPPER_OUTPUT_DIR xcodebuild -workspace $WORKSPACE -scheme $SCHEME -sdk iphonesimulator -destination "$DESTINATION"

  echo "~~~ xcodebuild"
  xcodebuild test -workspace $WORKSPACE -scheme $SCHEME -enableCodeCoverage YES -derivedDataPath build -sdk iphonesimulator -destination "$DESTINATION" build

  cd ../
  echo "~~~ xcov-to-sonar"

  # Run the xccov-to-sonarqube-generic.sh script
  (covert_xcresult_to_generic_xml test-harness/build/Logs/Test/*.xcresult/) >${RESULT_FILE}

  # Run sonar-scanner
  if ([ -z "$BUILDKITE_PULL_REQUEST" ] || [ "$BUILDKITE_PULL_REQUEST" == "false" ]); then
    echo "~~~ sonar-scanner on branch ${BUILDKITE_BRANCH}"
    sonar-scanner \
      -Dsonar.branch.name="${BUILDKITE_BRANCH}" \
      -Dsonar.cfamily.build-wrapper-output="${BUILD_WRAPPER_OUTPUT_DIR}" \
      -Dsonar.coverageReportPaths=${RESULT_FILE} \
  else
    echo "~~~ sonar-scanner on pr #${BUILDKITE_PULL_REQUEST}"
    sonar-scanner \
      -Dsonar.pullrequest.key="${BUILDKITE_PULL_REQUEST}" \
      -Dsonar.pullrequest.branch="${BUILDKITE_BRANCH}" \
      -Dsonar.pullrequest.base="${BUILDKITE_PULL_REQUEST_BASE_BRANCH}" \
      -Dsonar.cfamily.build-wrapper-output="${BUILD_WRAPPER_OUTPUT_DIR}" \
      -Dsonar.coverageReportPaths=${RESULT_FILE} \
  fi
}

function run_reactnative_ios_unit_tests() {
  echo "--- :test_tube: Running react-native iOS Unit Tests..."

  BASEDIR=$(pwd)

  ## Copy .npmrc files to the correct locations
  cp .npmrc react/library/
  cp .npmrc react/library/test-harness/

  ## Install react-native dependencies
  echo "~~~ Install react-native dependencies"
  cd react/library/
  npm ci

  cd test-harness
  npm ci

  ## Install ios dependencies
  echo "~~~ Install iOS dependencies"
  rbenv install --skip-existing
  bundle install --quiet
  cd ios
  bundle exec pod install

  ## Run ios unit tests
  echo "~~~ xcodebuild"
  xcodebuild -workspace $WORKSPACE -scheme $SCHEME -sdk iphonesimulator -destination "$DESTINATION"
  xcodebuild test -workspace $WORKSPACE -scheme $SCHEME -sdk iphonesimulator -destination "$DESTINATION"
}

if [[ "$SKIP" == "true" ]]; then
  echo "--- Skipping test as skip-test was set to true"
  exit 0
fi

# Check if the platform is set to contract or library and perform steps accordingly
if [[ "$PLATFORM" == "ios-library" ]]; then
  run_ios_unit_tests_and_sonar
elif [[ "$PLATFORM" == "react-library" ]]; then
  run_reactnative_ios_unit_tests
else
  echo "--- :warning: Platform needs to be one of these: [ios-library, react-library]"
  exit 0
fi
